---
- name: Create Multiple EPGs Dynamically using a Sequence
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    # APIC 및 상위 객체 정보
    apic_host: "192.168.120.11"
    apic_username: "admin"
    apic_password: "!@345Qwert"
    validate_certs: false
    aci_tenant: "gohome"
    aci_ap: "gocompany"

    # EPG 이름과 연결될 BD를 정의
    epg_prefix: "Web-EPG"
    target_bd: "Web-Servers-BD"

  tasks:
    - name: Create 50 EPGs from 01 to 50
      cisco.aci.aci_epg:
        host: "{{ apic_host }}"
        username: "{{ apic_username }}"
        password: "{{ apic_password }}"
        validate_certs: "{{ validate_certs }}"
        tenant: "{{ aci_tenant }}"
        ap: "{{ aci_ap }}"
        epg: "{{ epg_prefix }}-{{ '%02d' | format(item | int) }}"  # 'Web-EPG-01', 'Web-EPG-02', ...
        bd: "{{ target_bd }}"
        description: "Managed by Ansible - {{ epg_prefix }}-{{ '%02d' | format(item | int) }}"
        state: present
      delegate_to: localhost
      with_sequence: start=1 end=50   # 1부터 50까지의 숫자를 생성하여 반복
